const nom = new Set();
nom.add('Plinio');
nom.add('Alejandro');
nom.add('José');
nom.add('Leslie');
nom.add('Gonzalo');
nom.add('Ignacio');
nom.add('Alan');
nom.add('Alex');
nom.add('Salvador');
nom.add('Carlos');
console.log(nom);